CREATE SCHEMA SILUTEL;
SET search_path TO SILUTEL;

CREATE TABLE SILUTEL.USER (
	Email VARCHAR(35) NOT NULL,
	Nama VARCHAR(35) NOT NULL,
	Alamat VARCHAR(100) NOT NULL,
	Password VARCHAR(20) NOT NULL,
	Role CHARACTER(2) NOT NULL,
	PRIMARY KEY (Email)
);

CREATE TABLE SILUTEL.USER_TELEPON (
	Email VARCHAR(35) NOT NULL,
	Telepon VARCHAR(20) NOT NULL,
	PRIMARY KEY (Email, Telepon),
	FOREIGN KEY (Email) REFERENCES SILUTEL.USER(Email) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE SILUTEL.STAF_LAUNDRY (
	Email VARCHAR(35) NOT NULL,
	Lantai SMALLINT NOT NULL,
	PRIMARY KEY (Email),
	FOREIGN KEY (Email) REFERENCES SILUTEL.USER(Email) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE SILUTEL.STAF_INVENTORI_KAMAR (
	Email VARCHAR(35) NOT NULL,
	JamTerbang SMALLINT NOT NULL,
	PRIMARY KEY (Email),
	FOREIGN KEY (Email) REFERENCES SILUTEL.USER(Email) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE SILUTEL.LAUNDRY_STAF_LAUNDRY(
	EmailStaf VARCHAR(35) NOT NULL,
	Waktu TIMESTAMP NOT NULL,
	Total INTEGER NOT NULL,
	PRIMARY KEY (EmailStaf, Waktu),
	FOREIGN KEY (EmailStaf) REFERENCES STAF_LAUNDRY(Email) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE SILUTEL.TAMU(
	Id VARCHAR(20) NOT NULL,
	Nama VARCHAR(35) NOT NULL,
	Alamat VARCHAR(100) NOT NULL,
	PRIMARY KEY (Id)
);

CREATE TABLE SILUTEL.TAMU_TELEPON(
	IdTamu VARCHAR(20) NOT NULL,
	Telepon VARCHAR(20) NOT NULL,
	PRIMARY KEY (IdTamu, Telepon),
	FOREIGN KEY (IdTamu) REFERENCES TAMU(Id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE SILUTEL.INVOICE(
	NomorInvoice CHAR(6) PRIMARY KEY,
	TanggalDatang TIMESTAMP NOT NULL,
	TanggalPergi TIMESTAMP NOT NULL,
	Jumlah SMALLINT NOT NULL,
	IdTamu VARCHAR(20) NOT NULL,
	Discount INT NOT NULL,
	Total INT NOT NULL,
	FOREIGN KEY (IdTamu) REFERENCES TAMU(Id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE SILUTEL.TIPE_KAMAR(
	Nama VARCHAR(20) PRIMARY KEY,
	Kapasitas SMALLINT NOT NULL,
	Deskripsi VARCHAR(100) NOT NULL,
	Harga INT NOT NULL,
	JumlahRuangan SMALLINT NOT NULL
);

CREATE TABLE SILUTEL.KAMAR(
    Nomor SMALLINT NOT NULL,
    Lantai SMALLINT NOT NULL,
    NamaTipeKamar VARCHAR(20) NOT NULL,
	PRIMARY KEY (Nomor, Lantai),
	FOREIGN KEY (NamaTipeKamar) REFERENCES TIPE_KAMAR(Nama) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE SILUTEL.INVOICE_KAMAR(
    NomorInvoice CHAR(6) NOT NULL,
    NomorKamar SMALLINT NOT NULL,
    LantaiKamar SMALLINT NOT NULL,
    PRIMARY KEY (NomorInvoice, NomorKamar, LantaiKamar),
	FOREIGN KEY (NomorInvoice) REFERENCES INVOICE(NomorInvoice) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (NomorKamar, LantaiKamar) REFERENCES KAMAR(Nomor, Lantai) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE SILUTEL.INVENTORI(
	Nama VARCHAR(20) NOT NULL,
	Merk VARCHAR(20) NOT NULL,
	Stok SMALLINT NOT NULL,
	PRIMARY KEY (Nama, Merk)
);

CREATE TABLE SILUTEL.INVENTORI_TIPE_KAMAR(
	NamaTipeKamar VARCHAR(20) NOT NULL,
	NamaInventori VARCHAR(20) NOT NULL,
	Merk VARCHAR(20) NOT NULL,
	Jumlah SMALLINT NOT NULL,
	PRIMARY KEY (NamaTipeKamar, NamaInventori, Merk),
	FOREIGN KEY (NamaTipeKamar) REFERENCES TIPE_KAMAR(Nama) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (NamaInventori, Merk) REFERENCES INVENTORI(Nama, Merk) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE SILUTEL.LAUNDRY_INVENTORI(
	Nama VARCHAR(20) NOT NULL,
	Merk VARCHAR(20) NOT NULL,
	EmailStaf VARCHAR(35) NOT NULL,
	Waktu TIMESTAMP NOT NULL,
	Jumlah SMALLINT NOT NULL,
	HargaSatuan INTEGER NOT NULL,
	TanggalAmbil TIMESTAMP NOT NULL,
	PRIMARY KEY (Nama, Merk, EmailStaf, Waktu),
	FOREIGN KEY (Nama, Merk) REFERENCES INVENTORI(Nama, Merk) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (EmailStaf, Waktu) REFERENCES LAUNDRY_STAF_LAUNDRY(EmailStaf, Waktu) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE SILUTEL.SUPPLIER(
	Nama VARCHAR(35) NOT NULL,
    Alamat VARCHAR(100) NOT NULL,
    Email VARCHAR(35) NOT NULL,
    PRIMARY KEY (Nama)
);

CREATE TABLE SILUTEL.SUPPLIER_TELEPON(
    Nama VARCHAR(35) NOT NULL,
    Telepon VARCHAR(20) NOT NULL,
    PRIMARY KEY (Nama, Telepon),
    FOREIGN KEY (Nama) REFERENCES SUPPLIER(Nama) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE SILUTEL.PEMBELIAN(
    NomorNota CHAR(6) NOT NULL,
    Waktu TIMESTAMP NOT NULL,
    NamaSupplier VARCHAR(35),
    EmailStaf VARCHAR(35),
    PRIMARY KEY (NomorNota),
    FOREIGN KEY (NamaSupplier) REFERENCES SUPPLIER(Nama) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (EmailStaf) REFERENCES STAF_INVENTORI_KAMAR ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE SILUTEL.PEMBELIAN_INVENTORI(
    NomorNota CHAR(6) NOT NULL,
    Nama VARCHAR(20) NOT NULL,
    Merk VARCHAR(20) NOT NULL,
    Jumlah SMALLINT NOT NULL,
    HargaSatuan INTEGER NOT NULL,
    PRIMARY KEY (NomorNota, Nama, Merk),
    FOREIGN KEY (NomorNota) REFERENCES PEMBELIAN(NomorNota) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (Nama, Merk) REFERENCES INVENTORI(Nama, Merk) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE SILUTEL.STAF_MENGGANTI_INVENTORI(
    Nama VARCHAR(20) NOT NULL,
    Merk VARCHAR(20) NOT NULL,
    EmailStaf VARCHAR(35) NOT NULL,
    Waktu TIMESTAMP NOT NULL,
    Jumlah SMALLINT NOT NULL,
    Alasan TEXT,
    PRIMARY KEY (Nama, Merk, EmailStaf),
    FOREIGN KEY (Nama, Merk) REFERENCES INVENTORI(Nama, Merk) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (EmailStaf) REFERENCES STAF_INVENTORI_KAMAR
);
